name: terraform-ci
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt (check)
        run: terraform -chdir=terraform fmt -check

      - name: Terraform init (no backend)
        run: terraform -chdir=terraform init -backend=false -input=false

      - name: Terraform validate
        run: terraform -chdir=terraform validate -no-color
