name: terraform-ci

on:
  push:
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        run: terraform -chdir=terraform fmt -check

      - name: Terraform init (no backend)
        run: terraform -chdir=terraform init -backend=false

      - name: Terraform validate
        run: terraform -chdir=terraform validate -no-color
